INFO 2025-10-24 12:28:08,949 cli 26161 4354569728 Starting server at tcp:port=8000:interface=127.0.0.1
INFO 2025-10-24 12:28:08,950 server 26161 4354569728 HTTP/2 support enabled
INFO 2025-10-24 12:28:08,950 server 26161 4354569728 Configuring endpoint tcp:port=8000:interface=127.0.0.1
INFO 2025-10-24 12:28:08,951 server 26161 4354569728 Listening on TCP address 127.0.0.1:8000
INFO 2025-10-24 12:28:19,264 crypto_api_service 26161 123145473003520 CoinGecko API success: fetched 5 coins
INFO 2025-10-24 12:28:19,268 crypto_api_service 26161 123145473003520 Successfully fetched data from _fetch_from_coingecko
INFO 2025-10-24 12:28:19,282 crypto_api_service 26161 123145473003520 Updated 5 cryptocurrencies
INFO 2025-10-24 12:28:19,284 user_views 26161 123145473003520 Cryptocurrency data updated successfully
WARNING 2025-10-24 12:28:19,478 log 26161 123145541234688 Not Found: /static/assets/css/market.css
WARNING 2025-10-24 12:28:19,500 log 26161 123145541234688 Not Found: /static/assets/js/market.js
WARNING 2025-10-24 12:28:20,045 log 26161 123145541234688 Not Found: /static/assets/css/market.css
WARNING 2025-10-24 12:28:26,789 log 26161 123145541234688 Not Found: /static/assets/css/market.css
WARNING 2025-10-24 12:28:26,820 log 26161 123145541234688 Not Found: /static/assets/js/market.js
WARNING 2025-10-24 12:28:26,850 log 26161 123145541234688 Not Found: /static/assets/css/market.css
INFO 2025-10-24 12:28:48,329 server 26161 4354569728 Killed 0 pending application instances
INFO 2025-10-24 12:37:46,776 cli 27057 4434867712 Starting server at tcp:port=8000:interface=127.0.0.1
INFO 2025-10-24 12:37:46,776 server 27057 4434867712 HTTP/2 support enabled
INFO 2025-10-24 12:37:46,776 server 27057 4434867712 Configuring endpoint tcp:port=8000:interface=127.0.0.1
INFO 2025-10-24 12:37:46,777 server 27057 4434867712 Listening on TCP address 127.0.0.1:8000
INFO 2025-10-24 12:38:02,237 crypto_api_service 27057 123145384062976 CoinGecko API success: fetched 5 coins
INFO 2025-10-24 12:38:02,242 crypto_api_service 27057 123145384062976 Successfully fetched data from _fetch_from_coingecko
INFO 2025-10-24 12:38:02,258 crypto_api_service 27057 123145384062976 Updated 5 cryptocurrencies
INFO 2025-10-24 12:38:02,259 user_views 27057 123145384062976 Cryptocurrency data updated successfully
INFO 2025-10-24 12:38:23,627 crypto_api_service 27057 123145401389056 CoinGecko: Fetched 721 data points for BTC
INFO 2025-10-24 12:38:33,963 crypto_api_service 27057 123145401389056 CoinGecko: Fetched 721 data points for BTC
INFO 2025-10-24 12:50:59,261 crypto_api_service 27057 123145401389056 CoinGecko API success: fetched 5 coins
INFO 2025-10-24 12:50:59,266 crypto_api_service 27057 123145401389056 Successfully fetched data from _fetch_from_coingecko
INFO 2025-10-24 12:50:59,284 crypto_api_service 27057 123145401389056 Updated 5 cryptocurrencies
INFO 2025-10-24 12:50:59,286 user_views 27057 123145401389056 Cryptocurrency data updated successfully
INFO 2025-10-24 13:10:26,038 crypto_api_service 27057 123145401389056 CoinGecko API success: fetched 5 coins
INFO 2025-10-24 13:10:26,041 crypto_api_service 27057 123145401389056 Successfully fetched data from _fetch_from_coingecko
INFO 2025-10-24 13:10:26,064 crypto_api_service 27057 123145401389056 Updated 5 cryptocurrencies
INFO 2025-10-24 13:10:26,065 user_views 27057 123145401389056 Cryptocurrency data updated successfully
INFO 2025-10-24 13:11:33,181 crypto_api_service 27057 123145401389056 CoinGecko API success: fetched 5 coins
INFO 2025-10-24 13:11:33,184 crypto_api_service 27057 123145401389056 Successfully fetched data from _fetch_from_coingecko
INFO 2025-10-24 13:11:33,201 crypto_api_service 27057 123145401389056 Updated 5 cryptocurrencies
WARNING 2025-10-24 13:11:33,372 log 27057 123145418178560 Not Found: /static/js/chart.js
INFO 2025-10-24 13:11:54,920 server 27057 4434867712 Killed 0 pending application instances
INFO 2025-10-24 13:12:01,379 autoreload 27703 4701754880 Watching for file changes with StatReloader
INFO 2025-10-24 13:12:14,050 crypto_api_service 27703 123145354883072 CoinGecko API success: fetched 5 coins
INFO 2025-10-24 13:12:14,056 crypto_api_service 27703 123145354883072 Successfully fetched data from _fetch_from_coingecko
INFO 2025-10-24 13:12:14,074 crypto_api_service 27703 123145354883072 Updated 5 cryptocurrencies
ERROR 2025-10-24 13:33:23,641 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:33:29,648 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:33:37,474 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:33:48,478 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:33:54,431 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:34:00,430 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:34:06,495 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:34:12,434 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:34:18,469 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:34:23,688 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:34:29,771 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:34:35,903 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:34:43,722 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:34:54,405 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:35:05,300 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:35:12,668 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:35:23,121 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:35:30,014 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:35:39,845 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:35:49,823 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:36:00,329 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:36:09,578 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:36:17,168 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:36:26,523 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:36:35,212 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:36:45,360 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:36:52,422 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:37:01,718 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:37:10,646 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:37:18,217 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:37:24,999 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:37:31,525 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:37:42,137 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:37:51,563 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:38:00,613 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:38:10,143 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:38:16,737 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:38:24,952 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:38:34,344 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:38:43,154 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:38:50,723 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:39:00,307 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:39:09,945 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:39:19,652 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:39:28,875 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:39:37,608 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:39:47,394 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:39:56,917 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:40:05,027 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:40:11,571 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:40:21,146 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:40:28,493 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:40:38,283 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
ERROR 2025-10-24 13:40:47,168 log 27703 123145354883072 Internal Server Error: /ws/market/
Traceback (most recent call last):
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/.pyenv/versions/3.11.8/lib/python3.11/site-packages/asgiref/sync.py", line 270, in __call__
    self.awaitable(*args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MarketConsumer() missing 2 required positional arguments: 'receive' and 'send'
INFO 2025-10-24 13:43:00,887 cli 28341 4596971008 Starting server at tcp:port=8000:interface=127.0.0.1
INFO 2025-10-24 13:43:00,888 server 28341 4596971008 HTTP/2 support enabled
INFO 2025-10-24 13:43:00,888 server 28341 4596971008 Configuring endpoint tcp:port=8000:interface=127.0.0.1
INFO 2025-10-24 13:43:00,889 server 28341 4596971008 Listening on TCP address 127.0.0.1:8000
WARNING 2025-10-24 13:43:05,488 log 28341 123145605988352 Not Found: /static/js/market.js
INFO 2025-10-24 13:43:32,704 server 28341 4596971008 Killed 0 pending application instances
INFO 2025-10-24 13:43:46,117 cli 28697 4631967232 Starting server at tcp:port=8000:interface=127.0.0.1
INFO 2025-10-24 13:43:46,117 server 28697 4631967232 HTTP/2 support enabled
INFO 2025-10-24 13:43:46,117 server 28697 4631967232 Configuring endpoint tcp:port=8000:interface=127.0.0.1
INFO 2025-10-24 13:43:46,118 server 28697 4631967232 Listening on TCP address 127.0.0.1:8000
WARNING 2025-10-24 13:43:49,877 log 28697 123145495535616 Not Found: /static/js/market.js
INFO 2025-10-24 13:57:46,945 server 28697 4631967232 Killed 0 pending application instances
INFO 2025-10-24 13:59:57,498 cli 28996 4702348800 Starting server at tcp:port=8000:interface=127.0.0.1
INFO 2025-10-24 13:59:57,499 server 28996 4702348800 HTTP/2 support enabled
INFO 2025-10-24 13:59:57,499 server 28996 4702348800 Configuring endpoint tcp:port=8000:interface=127.0.0.1
INFO 2025-10-24 13:59:57,501 server 28996 4702348800 Listening on TCP address 127.0.0.1:8000
WARNING 2025-10-24 14:00:01,689 log 28996 123145446797312 Not Found: /static/js/portfolio.js
WARNING 2025-10-24 14:00:01,691 log 28996 123145480376320 Not Found: /static/js/portfolioSocket.js
WARNING 2025-10-24 14:00:01,692 log 28996 123145463586816 Not Found: /static/js/portfolioCharts.js
INFO 2025-10-24 14:00:01,740 consumers 28996 4702348800 Market WebSocket connected: specific..inmemory!aXITqOKfvubA
INFO 2025-10-24 14:01:27,950 server 28996 4702348800 Killed 1 pending application instances
INFO 2025-10-24 14:02:06,491 autoreload 29278 4363834880 Watching for file changes with StatReloader
WARNING 2025-10-24 14:02:08,567 log 29278 123145485402112 Not Found: /ws/market/
WARNING 2025-10-24 14:02:09,911 log 29278 123145485402112 Not Found: /ws/market/
WARNING 2025-10-24 14:02:15,152 log 29278 123145485402112 Not Found: /ws/market/
